using IDSR.CondorReader.Core.ns11.Converters;
using Repo2.Core.ns11.Extensions;
using System;
using System.Data;

namespace IDSR.CondorReader.Core.ns11.DomainModels
{
    public class CdrPOS_Products
    {
        public CdrPOS_Products(IDataRecord r)
        {
            ProductID             = r.ToInt_    ( 0);// int?      integer,
            ProductCode           = r.ToText    ( 1);// string    varchar(20) NOT NULL COLLATE NOCASE,
            Barcode               = r.ToText    ( 2);// string    varchar(20) NOT NULL COLLATE NOCASE,
            PriceModeCode         = r.ToText    ( 3);// string    varchar(2) COLLATE NOCASE DEFAULT 'R',
            Description           = r.ToText    ( 4);// string    varchar(25) NOT NULL COLLATE NOCASE,
            uom                   = r.ToText    ( 5);// string    varchar(6) NOT NULL COLLATE NOCASE DEFAULT 'PC',
            qty                   = r.ToDecimal ( 6);// decimal   numeric NOT NULL DEFAULT 1,
            markup                = r.ToDecimal ( 7);// decimal   numeric NOT NULL DEFAULT 0,
            srp                   = r.ToDecimal ( 8);// decimal   numeric NOT NULL DEFAULT 0,
            MarginalPriceEnabled  = r.ToBool    ( 9);// bool      bit NOT NULL DEFAULT 0,
            unitssold1            = r.ToDecimal (10);// decimal   numeric NOT NULL DEFAULT 0,
            unitssold2            = r.ToDecimal (11);// decimal   numeric NOT NULL DEFAULT 0,
            unitssold3            = r.ToDecimal (12);// decimal   numeric NOT NULL DEFAULT 0,
            markup1               = r.ToDecimal (13);// decimal   numeric NOT NULL DEFAULT 0,
            markup2               = r.ToDecimal (14);// decimal   numeric NOT NULL DEFAULT 0,
            markup3               = r.ToDecimal (15);// decimal   numeric NOT NULL DEFAULT 0,
            srp1                  = r.ToDecimal (16);// decimal   numeric NOT NULL DEFAULT 0,
            srp2                  = r.ToDecimal (17);// decimal   numeric NOT NULL DEFAULT 0,
            srp3                  = r.ToDecimal (18);// decimal   numeric NOT NULL DEFAULT 0,
            MarkdownEnabled       = r.ToBool    (19);// bool      bit NOT NULL DEFAULT 0,
            MarkdownDateFrom      = r.ToDate_   (20);// DateTime? datetime,
            MarkdownDateTo        = r.ToDate_   (21);// DateTime? datetime,
            MarkdownTimeFrom      = r.ToDate_   (22);// DateTime? datetime,
            MarkdownTimeTo        = r.ToDate_   (23);// DateTime? datetime,
            Markdown              = r.ToDecimal (24);// decimal   numeric DEFAULT 0,
            DiscountedSRP         = r.ToDecimal (25);// decimal   numeric DEFAULT 0,
            LastDateModified      = r.ToDate    (26);// DateTime  datetime DEFAULT (CURRENT_TIMESTAMP),
            Points                = r.ToDecimal (27);// decimal   numeric NOT NULL DEFAULT 0,
            PointsType            = r.ToShort   (28);// short     smallint NOT NULL DEFAULT 0,
            PointsEnabled         = r.ToBool    (29);// bool      bit NOT NULL DEFAULT 0,
            PointsDateFrom        = r.ToDate_   (30);// DateTime? datetime,
            PointsDateTo          = r.ToDate_   (31);// DateTime? datetime,
            PointsTimeFrom        = r.ToDate_   (32);// DateTime? datetime,
            PointsTimeTo          = r.ToDate_   (33);// DateTime? datetime,
            HotProduct            = r.ToBool    (34);// bool      bit NOT NULL DEFAULT 0,
            CONSIGNED             = r.ToBool    (35);// bool      bit NOT NULL DEFAULT 0,
            computedSRP           = r.ToDecimal (36);// decimal   numeric NOT NULL DEFAULT 0,
            pVatable              = r.ToBool    (37);// bool      bit DEFAULT 0,
            pVatPercent           = r.ToInt     (38);// int       integer DEFAULT 0,
            SeniorCitizenTag      = r.ToBool    (39);// bool      bit NOT NULL DEFAULT 0,
            DiscountType1         = r.ToBool    (40);// bool      bit NOT NULL DEFAULT 0,
            DiscountType2         = r.ToBool    (41);// bool      bit NOT NULL DEFAULT 0,
            DiscountType3         = r.ToBool    (42);// bool      bit NOT NULL DEFAULT 0,
            DiscountType4         = r.ToBool    (43);// bool      bit NOT NULL DEFAULT 0,
            DiscountType5         = r.ToBool    (44);// bool      bit NOT NULL DEFAULT 0,
            DiscountType6         = r.ToBool    (45);// bool      bit NOT NULL DEFAULT 0,
            DiscountType7         = r.ToBool    (46);// bool      bit NOT NULL DEFAULT 0,
            DiscountType8         = r.ToBool    (47);// bool      bit NOT NULL DEFAULT 0,
            DiscountType9         = r.ToBool    (48);// bool      bit NOT NULL DEFAULT 0,
            DiscountType10        = r.ToBool    (49);// bool      bit NOT NULL DEFAULT 0,
            DiplomatTag           = r.ToBool    (50);// bool      bit NOT NULL DEFAULT 0,
            WatchZeroInventory    = r.ToBool    (51);// bool      bit NOT NULL DEFAULT 0,
            DiscountCode          = r.ToText    (52);// string    varchar(4) COLLATE NOCASE DEFAULT '',
            Discount              = r.ToDecimal (53);// decimal   numeric NOT NULL DEFAULT 0,
            SeniorDiscountPercent = r.ToDecimal (54);// decimal   integer NOT NULL DEFAULT 0,
            TaxID                 = r.ToDecimal (55);// decimal   integer NOT NULL DEFAULT 0,
            MixandMatch           = r.ToDecimal (56);// decimal   integer NOT NULL DEFAULT 0,
            LinkedItem            = r.ToText    (57);// string    varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
            TimeBasedInterval     = r.ToInt     (58);// int       integer NOT NULL DEFAULT 0,
            TimeBasedCode         = r.ToText    (59);// string    varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
            ServiceCharge         = r.ToBool    (60);// bool      bit NOT NULL DEFAULT 0,
            PWDDiscountPercent    = r.ToDecimal (61);// decimal   numeric NOT NULL DEFAULT 0,
            MARGIN                = r.ToDecimal (62);// decimal   numeric NOT NULL DEFAULT 0,
            MARGIN1               = r.ToDecimal (63);// decimal   numeric NOT NULL DEFAULT 0,
            MARGIN2               = r.ToDecimal (64);// decimal   numeric NOT NULL DEFAULT 0,
            MARGIN3               = r.ToDecimal (65);// decimal   numeric NOT NULL DEFAULT 0

            ParsedBarCode         = Barcode.ToBarCode(Description);
        }

        public int?       ProductID             { get; }// integer,
        public string     ProductCode           { get; }// varchar(20) NOT NULL COLLATE NOCASE,
        public string     Barcode               { get; }// varchar(20) NOT NULL COLLATE NOCASE,
        public string     PriceModeCode         { get; }// varchar(2) COLLATE NOCASE DEFAULT 'R',
        public string     Description           { get; }// varchar(25) NOT NULL COLLATE NOCASE,
        public string     uom                   { get; }// varchar(6) NOT NULL COLLATE NOCASE DEFAULT 'PC',
        public decimal    qty                   { get; }// numeric NOT NULL DEFAULT 1,
        public decimal    markup                { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    srp                   { get; }// numeric NOT NULL DEFAULT 0,
        public bool       MarginalPriceEnabled  { get; }// bit NOT NULL DEFAULT 0,
        public decimal    unitssold1            { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    unitssold2            { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    unitssold3            { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    markup1               { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    markup2               { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    markup3               { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    srp1                  { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    srp2                  { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    srp3                  { get; }// numeric NOT NULL DEFAULT 0,
        public bool       MarkdownEnabled       { get; }// bit NOT NULL DEFAULT 0,
        public DateTime?  MarkdownDateFrom      { get; }// datetime,
        public DateTime?  MarkdownDateTo        { get; }// datetime,
        public DateTime?  MarkdownTimeFrom      { get; }// datetime,
        public DateTime?  MarkdownTimeTo        { get; }// datetime,
        public decimal    Markdown              { get; }// numeric DEFAULT 0,
        public decimal    DiscountedSRP         { get; }// numeric DEFAULT 0,
        public DateTime   LastDateModified      { get; }// datetime DEFAULT (CURRENT_TIMESTAMP),
        public decimal    Points                { get; }// numeric NOT NULL DEFAULT 0,
        public short      PointsType            { get; }// smallint NOT NULL DEFAULT 0,
        public bool       PointsEnabled         { get; }// bit NOT NULL DEFAULT 0,
        public DateTime?  PointsDateFrom        { get; }// datetime,
        public DateTime?  PointsDateTo          { get; }// datetime,
        public DateTime?  PointsTimeFrom        { get; }// datetime,
        public DateTime?  PointsTimeTo          { get; }// datetime,
        public bool       HotProduct            { get; }// bit NOT NULL DEFAULT 0,
        public bool       CONSIGNED             { get; }// bit NOT NULL DEFAULT 0,
        public decimal    computedSRP           { get; }// numeric NOT NULL DEFAULT 0,
        public bool       pVatable              { get; }// bit DEFAULT 0,
        public int        pVatPercent           { get; }// integer DEFAULT 0,
        public bool       SeniorCitizenTag      { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType1         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType2         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType3         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType4         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType5         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType6         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType7         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType8         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType9         { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiscountType10        { get; }// bit NOT NULL DEFAULT 0,
        public bool       DiplomatTag           { get; }// bit NOT NULL DEFAULT 0,
        public bool       WatchZeroInventory    { get; }// bit NOT NULL DEFAULT 0,
        public string     DiscountCode          { get; }// varchar(4) COLLATE NOCASE DEFAULT '',
        public decimal    Discount              { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    SeniorDiscountPercent { get; }// integer NOT NULL DEFAULT 0,
        public decimal    TaxID                 { get; }// integer NOT NULL DEFAULT 0,
        public decimal    MixandMatch           { get; }// integer NOT NULL DEFAULT 0,
        public string     LinkedItem            { get; }// varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
        public int        TimeBasedInterval     { get; }// integer NOT NULL DEFAULT 0,
        public string     TimeBasedCode         { get; }// varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
        public bool       ServiceCharge         { get; }// bit NOT NULL DEFAULT 0,
        public decimal    PWDDiscountPercent    { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    MARGIN                { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    MARGIN1               { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    MARGIN2               { get; }// numeric NOT NULL DEFAULT 0,
        public decimal    MARGIN3               { get; }// numeric NOT NULL DEFAULT 0

        public ulong      ParsedBarCode         { get; }
    }
}
/*
CREATE TABLE [POS_Products] (
    [ProductID            ]	integer,
    [ProductCode          ]	varchar(20) NOT NULL COLLATE NOCASE,
    [Barcode              ]	varchar(20) NOT NULL COLLATE NOCASE,
    [PriceModeCode        ]	varchar(2) COLLATE NOCASE DEFAULT 'R',
    [Description          ]	varchar(25) NOT NULL COLLATE NOCASE,
    [uom                  ]	varchar(6) NOT NULL COLLATE NOCASE DEFAULT 'PC',
    [qty                  ]	numeric NOT NULL DEFAULT 1,
    [markup               ]	numeric NOT NULL DEFAULT 0,
    [srp                  ]	numeric NOT NULL DEFAULT 0,
    [MarginalPriceEnabled ]	bit NOT NULL DEFAULT 0,
    [unitssold1           ]	numeric NOT NULL DEFAULT 0,
    [unitssold2           ]	numeric NOT NULL DEFAULT 0,
    [unitssold3           ]	numeric NOT NULL DEFAULT 0,
    [markup1              ]	numeric NOT NULL DEFAULT 0,
    [markup2              ]	numeric NOT NULL DEFAULT 0,
    [markup3              ]	numeric NOT NULL DEFAULT 0,
    [srp1                 ]	numeric NOT NULL DEFAULT 0,
    [srp2                 ]	numeric NOT NULL DEFAULT 0,
    [srp3                 ]	numeric NOT NULL DEFAULT 0,
    [MarkdownEnabled      ]	bit NOT NULL DEFAULT 0,
    [MarkdownDateFrom     ]	datetime,
    [MarkdownDateTo       ]	datetime,
    [MarkdownTimeFrom     ]	datetime,
    [MarkdownTimeTo       ]	datetime,
    [Markdown             ]	numeric DEFAULT 0,
    [DiscountedSRP        ]	numeric DEFAULT 0,
    [LastDateModified     ]	datetime DEFAULT (CURRENT_TIMESTAMP),
    [Points               ]	numeric NOT NULL DEFAULT 0,
    [PointsType           ]	smallint NOT NULL DEFAULT 0,
    [PointsEnabled        ]	bit NOT NULL DEFAULT 0,
    [PointsDateFrom       ]	datetime,
    [PointsDateTo         ]	datetime,
    [PointsTimeFrom       ]	datetime,
    [PointsTimeTo         ]	datetime,
    [HotProduct           ]	bit NOT NULL DEFAULT 0,
    [CONSIGNED            ]	bit NOT NULL DEFAULT 0,
    [computedSRP          ]	numeric NOT NULL DEFAULT 0,
    [pVatable             ]	bit DEFAULT 0,
    [pVatPercent          ]	integer DEFAULT 0,
    [SeniorCitizenTag     ]	bit NOT NULL DEFAULT 0,
    [DiscountType1        ]	bit NOT NULL DEFAULT 0,
    [DiscountType2        ]	bit NOT NULL DEFAULT 0,
    [DiscountType3        ]	bit NOT NULL DEFAULT 0,
    [DiscountType4        ]	bit NOT NULL DEFAULT 0,
    [DiscountType5        ]	bit NOT NULL DEFAULT 0,
    [DiscountType6        ]	bit NOT NULL DEFAULT 0,
    [DiscountType7        ]	bit NOT NULL DEFAULT 0,
    [DiscountType8        ]	bit NOT NULL DEFAULT 0,
    [DiscountType9        ]	bit NOT NULL DEFAULT 0,
    [DiscountType10       ]	bit NOT NULL DEFAULT 0,
    [DiplomatTag          ]	bit NOT NULL DEFAULT 0,
    [WatchZeroInventory   ]	bit NOT NULL DEFAULT 0,
    [DiscountCode         ]	varchar(4) COLLATE NOCASE DEFAULT '',
    [Discount             ]	numeric NOT NULL DEFAULT 0,
    [SeniorDiscountPercent]	integer NOT NULL DEFAULT 0,
    [TaxID                ]	integer NOT NULL DEFAULT 0,
    [MixandMatch          ]	integer NOT NULL DEFAULT 0,
    [LinkedItem           ]	varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
    [TimeBasedInterval    ]	integer NOT NULL DEFAULT 0,
    [TimeBasedCode        ]	varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
    [ServiceCharge        ]	bit NOT NULL DEFAULT 0,
    [PWDDiscountPercent   ]	numeric NOT NULL DEFAULT 0,
    [MARGIN               ]	numeric NOT NULL DEFAULT 0,
    [MARGIN1              ]	numeric NOT NULL DEFAULT 0,
    [MARGIN2              ]	numeric NOT NULL DEFAULT 0,
    [MARGIN3              ]	numeric NOT NULL DEFAULT 0
);
 */
