using IDSR.CondorReader.Core.ns11.Converters;
using Repo2.Core.ns11.Extensions;
using System;
using System.Data;

namespace IDSR.CondorReader.Core.ns11.DomainModels
{
    public class CdrTransactionHeader
    {
        public CdrTransactionHeader(IDataRecord r)
        {
            TransactionNo          = r.ToLong    ( 0);//integer DEFAULT 0,
            CustomerCode           = r.ToText    ( 1);//varchar(20) COLLATE NOCASE DEFAULT '',
            Description            = r.ToText    ( 2);//varchar(40) COLLATE NOCASE DEFAULT '',
            SubTotal               = r.ToDecimal ( 3);//numeric DEFAULT 0,
            GrandTotal             = r.ToDecimal ( 4);//numeric DEFAULT 0,
            DownPayments           = r.ToDecimal ( 5);//numeric DEFAULT 0,
            Discount               = r.ToDecimal ( 6);//numeric DEFAULT 0,
            AmountDiscounted       = r.ToDecimal ( 7);//numeric DEFAULT 0,
            Allowance              = r.ToDecimal ( 8);//numeric DEFAULT 0,
            ChargeDiscount         = r.ToDecimal ( 9);//numeric DEFAULT 0,
            ChargeAllowance        = r.ToDecimal (10);//numeric DEFAULT 0,
            ChargeAmountDiscounted = r.ToDecimal (11);//numeric DEFAULT 0,
            Shift                  = (int)r.ToLong (12);//integer NOT NULL DEFAULT 0,
            UserID                 = r.ToText    (13);//varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
            TerminalNo             = r.ToText    (14);//varchar(10) NOT NULL COLLATE NOCASE DEFAULT '',
            BranchCode             = r.ToText    (15);//varchar(10) NOT NULL COLLATE NOCASE DEFAULT '',
            LogDate                = r.ToDate    (16);//datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
            DateTime               = r.ToDate    (17);//datetime DEFAULT (CURRENT_TIMESTAMP),
            Voided                 = r.ToBool    (18);//bit NOT NULL DEFAULT 0,
            VoidRemarks            = r.ToText    (19);//varchar(40) COLLATE NOCASE DEFAULT '',
            BaggerID               = r.ToDecimal (20);//numeric NOT NULL DEFAULT 0,
            Senior                 = r.ToBool    (21);//bit NOT NULL DEFAULT 0,
            ReturnSubtotal         = r.ToDecimal (22);//numeric DEFAULT 0,
            SalesmanID             = r.ToDecimal (23);//numeric DEFAULT 0,
            TimeOfFirstScan        = r.ToDate_   (24);//datetime,
            TimeOfLastScan         = r.ToDate_   (25);//datetime,
            TimeCashedOut          = r.ToDate_   (26);//datetime,
            TimeBaggingStarted     = r.ToDate_   (27);//datetime,
            TimeBaggingFinished    = r.ToDate_   (28);//datetime,
            Layaway                = r.ToBool    (29);//bit DEFAULT 0,
            LayawayNumber          = (int?)r.ToLong_  (30);//integer,
            RoundedValue           = r.ToDecimal (31);//numeric NOT NULL DEFAULT 0,
            OnlineDealsSM          = (int)r.ToLong     (32);//integer DEFAULT 0,
            SERVICECHARGE          = r.ToDecimal (33);//numeric NOT NULL DEFAULT 0,
            ORDERTYPE              = r.ToText    (34);//varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
            GUESTCOUNT             = (int)r.ToLong (35);//integer NOT NULL DEFAULT 0,
            SCID                   = r.ToText    (36);//varchar(40) NOT NULL COLLATE NOCASE DEFAULT '',
            PWDID                  = r.ToText    (37);//varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
            SENIORCITIZENDISCQSR   = r.ToDecimal_(38);//numeric,
            SENIORCITIZENCOUNT     = r.ToDecimal_(39);//numeric

            ParsedCustomerCode     = CustomerCode.ToBarCode_();
        }


        public long        TransactionNo           { get; }//integer DEFAULT 0,
        public string      CustomerCode            { get; }//varchar(20) COLLATE NOCASE DEFAULT '',
        public string      Description             { get; }//varchar(40) COLLATE NOCASE DEFAULT '',
        public decimal     SubTotal                { get; }//numeric DEFAULT 0,
        public decimal     GrandTotal              { get; }//numeric DEFAULT 0,
        public decimal     DownPayments            { get; }//numeric DEFAULT 0,
        public decimal     Discount                { get; }//numeric DEFAULT 0,
        public decimal     AmountDiscounted        { get; }//numeric DEFAULT 0,
        public decimal     Allowance               { get; }//numeric DEFAULT 0,
        public decimal     ChargeDiscount          { get; }//numeric DEFAULT 0,
        public decimal     ChargeAllowance         { get; }//numeric DEFAULT 0,
        public decimal     ChargeAmountDiscounted  { get; }//numeric DEFAULT 0,
        public int         Shift                   { get; }//integer NOT NULL DEFAULT 0,
        public string      UserID                  { get; }//varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
        public string      TerminalNo              { get; }//varchar(10) NOT NULL COLLATE NOCASE DEFAULT '',
        public string      BranchCode              { get; }//varchar(10) NOT NULL COLLATE NOCASE DEFAULT '',
        public DateTime    LogDate                 { get; }//datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        public DateTime    DateTime                { get; }//datetime DEFAULT (CURRENT_TIMESTAMP),
        public bool        Voided                  { get; set; }//bit NOT NULL DEFAULT 0,
        public string      VoidRemarks             { get; }//varchar(40) COLLATE NOCASE DEFAULT '',
        public decimal     BaggerID                { get; }//numeric NOT NULL DEFAULT 0,
        public bool        Senior                  { get; }//bit NOT NULL DEFAULT 0,
        public decimal     ReturnSubtotal          { get; }//numeric DEFAULT 0,
        public decimal     SalesmanID              { get; }//numeric DEFAULT 0,
        public DateTime?   TimeOfFirstScan         { get; }//datetime,
        public DateTime?   TimeOfLastScan          { get; }//datetime,
        public DateTime?   TimeCashedOut           { get; }//datetime,
        public DateTime?   TimeBaggingStarted      { get; }//datetime,
        public DateTime?   TimeBaggingFinished     { get; }//datetime,
        public bool        Layaway                 { get; }//bit DEFAULT 0,
        public int?        LayawayNumber           { get; }//integer,
        public decimal     RoundedValue            { get; }//numeric NOT NULL DEFAULT 0,
        public int         OnlineDealsSM           { get; }//integer DEFAULT 0,
        public decimal     SERVICECHARGE           { get; }//numeric NOT NULL DEFAULT 0,
        public string      ORDERTYPE               { get; }//varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
        public int         GUESTCOUNT              { get; }//integer NOT NULL DEFAULT 0,
        public string      SCID                    { get; }//varchar(40) NOT NULL COLLATE NOCASE DEFAULT '',
        public string      PWDID                   { get; }//varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
        public decimal?    SENIORCITIZENDISCQSR    { get; }//numeric,
        public decimal?    SENIORCITIZENCOUNT      { get; }//numeric

        public ulong?      ParsedCustomerCode      { get; }
    }
}
/*
CREATE TABLE [FinishedTransaction] (
    [TransactionNo         ]	integer DEFAULT 0,
    [CustomerCode          ]	varchar(20) COLLATE NOCASE DEFAULT '',
    [Description           ]	varchar(40) COLLATE NOCASE DEFAULT '',
    [SubTotal              ]	numeric DEFAULT 0,
    [GrandTotal            ]	numeric DEFAULT 0,
    [DownPayments          ]	numeric DEFAULT 0,
    [Discount              ]	numeric DEFAULT 0,
    [AmountDiscounted      ]	numeric DEFAULT 0,
    [Allowance             ]	numeric DEFAULT 0,
    [ChargeDiscount        ]	numeric DEFAULT 0,
    [ChargeAllowance       ]	numeric DEFAULT 0,
    [ChargeAmountDiscounted]	numeric DEFAULT 0,
    [Shift                 ]	integer NOT NULL DEFAULT 0,
    [UserID                ]	varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
    [TerminalNo            ]	varchar(10) NOT NULL COLLATE NOCASE DEFAULT '',
    [BranchCode            ]	varchar(10) NOT NULL COLLATE NOCASE DEFAULT '',
    [LogDate               ]	datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    [DateTime              ]	datetime DEFAULT (CURRENT_TIMESTAMP),
    [Voided                ]	bit NOT NULL DEFAULT 0,
    [VoidRemarks           ]	varchar(40) COLLATE NOCASE DEFAULT '',
    [BaggerID              ]	numeric NOT NULL DEFAULT 0,
    [Senior                ]	bit NOT NULL DEFAULT 0,
    [ReturnSubtotal        ]	numeric DEFAULT 0,
    [SalesmanID            ]	numeric DEFAULT 0,
    [TimeOfFirstScan       ]	datetime,
    [TimeOfLastScan        ]	datetime,
    [TimeCashedOut         ]	datetime,
    [TimeBaggingStarted    ]	datetime,
    [TimeBaggingFinished   ]	datetime,
    [Layaway               ]	bit DEFAULT 0,
    [LayawayNumber         ]	integer,
    [RoundedValue          ]	numeric NOT NULL DEFAULT 0,
    [OnlineDealsSM         ]	integer DEFAULT 0,
    [SERVICECHARGE         ]	numeric NOT NULL DEFAULT 0,
    [ORDERTYPE             ]	varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
    [GUESTCOUNT            ]	integer NOT NULL DEFAULT 0,
    [SCID                  ]	varchar(40) NOT NULL COLLATE NOCASE DEFAULT '',
    [PWDID                 ]	varchar(20) NOT NULL COLLATE NOCASE DEFAULT '',
    [SENIORCITIZENDISCQSR  ]	numeric,
    [SENIORCITIZENCOUNT    ]	numeric
);

*/
